/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradesIndexRouteImport } from './routes/trades.index'
import { Route as TradesTradeIdRouteImport } from './routes/trades.$tradeId'
import { Route as BotBotIdRouteImport } from './routes/bot.$botId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesIndexRoute = TradesIndexRouteImport.update({
  id: '/trades/',
  path: '/trades/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesTradeIdRoute = TradesTradeIdRouteImport.update({
  id: '/trades/$tradeId',
  path: '/trades/$tradeId',
  getParentRoute: () => rootRouteImport,
} as any)
const BotBotIdRoute = BotBotIdRouteImport.update({
  id: '/bot/$botId',
  path: '/bot/$botId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bot/$botId': typeof BotBotIdRoute
  '/trades/$tradeId': typeof TradesTradeIdRoute
  '/trades/': typeof TradesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bot/$botId': typeof BotBotIdRoute
  '/trades/$tradeId': typeof TradesTradeIdRoute
  '/trades': typeof TradesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bot/$botId': typeof BotBotIdRoute
  '/trades/$tradeId': typeof TradesTradeIdRoute
  '/trades/': typeof TradesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bot/$botId' | '/trades/$tradeId' | '/trades/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bot/$botId' | '/trades/$tradeId' | '/trades'
  id: '__root__' | '/' | '/bot/$botId' | '/trades/$tradeId' | '/trades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BotBotIdRoute: typeof BotBotIdRoute
  TradesTradeIdRoute: typeof TradesTradeIdRoute
  TradesIndexRoute: typeof TradesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/': {
      id: '/trades/'
      path: '/trades'
      fullPath: '/trades/'
      preLoaderRoute: typeof TradesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/$tradeId': {
      id: '/trades/$tradeId'
      path: '/trades/$tradeId'
      fullPath: '/trades/$tradeId'
      preLoaderRoute: typeof TradesTradeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot/$botId': {
      id: '/bot/$botId'
      path: '/bot/$botId'
      fullPath: '/bot/$botId'
      preLoaderRoute: typeof BotBotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BotBotIdRoute: BotBotIdRoute,
  TradesTradeIdRoute: TradesTradeIdRoute,
  TradesIndexRoute: TradesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
