/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradesIndexRouteImport } from './routes/trades.index'
import { Route as ScoringIndexRouteImport } from './routes/scoring.index'
import { Route as BacktestsIndexRouteImport } from './routes/backtests.index'
import { Route as TradesTradeIdRouteImport } from './routes/trades.$tradeId'
import { Route as StrategyBotIdRouteImport } from './routes/strategy.$botId'
import { Route as ScoringSignalIdRouteImport } from './routes/scoring.$signalId'
import { Route as BotBotIdRouteImport } from './routes/bot.$botId'
import { Route as BacktestsRunIdRouteImport } from './routes/backtests.$runId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesIndexRoute = TradesIndexRouteImport.update({
  id: '/trades/',
  path: '/trades/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoringIndexRoute = ScoringIndexRouteImport.update({
  id: '/scoring/',
  path: '/scoring/',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestsIndexRoute = BacktestsIndexRouteImport.update({
  id: '/backtests/',
  path: '/backtests/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesTradeIdRoute = TradesTradeIdRouteImport.update({
  id: '/trades/$tradeId',
  path: '/trades/$tradeId',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyBotIdRoute = StrategyBotIdRouteImport.update({
  id: '/strategy/$botId',
  path: '/strategy/$botId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoringSignalIdRoute = ScoringSignalIdRouteImport.update({
  id: '/scoring/$signalId',
  path: '/scoring/$signalId',
  getParentRoute: () => rootRouteImport,
} as any)
const BotBotIdRoute = BotBotIdRouteImport.update({
  id: '/bot/$botId',
  path: '/bot/$botId',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestsRunIdRoute = BacktestsRunIdRouteImport.update({
  id: '/backtests/$runId',
  path: '/backtests/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/features': typeof FeaturesRoute
  '/settings': typeof SettingsRoute
  '/backtests/$runId': typeof BacktestsRunIdRoute
  '/bot/$botId': typeof BotBotIdRoute
  '/scoring/$signalId': typeof ScoringSignalIdRoute
  '/strategy/$botId': typeof StrategyBotIdRoute
  '/trades/$tradeId': typeof TradesTradeIdRoute
  '/backtests/': typeof BacktestsIndexRoute
  '/scoring/': typeof ScoringIndexRoute
  '/trades/': typeof TradesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/features': typeof FeaturesRoute
  '/settings': typeof SettingsRoute
  '/backtests/$runId': typeof BacktestsRunIdRoute
  '/bot/$botId': typeof BotBotIdRoute
  '/scoring/$signalId': typeof ScoringSignalIdRoute
  '/strategy/$botId': typeof StrategyBotIdRoute
  '/trades/$tradeId': typeof TradesTradeIdRoute
  '/backtests': typeof BacktestsIndexRoute
  '/scoring': typeof ScoringIndexRoute
  '/trades': typeof TradesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/features': typeof FeaturesRoute
  '/settings': typeof SettingsRoute
  '/backtests/$runId': typeof BacktestsRunIdRoute
  '/bot/$botId': typeof BotBotIdRoute
  '/scoring/$signalId': typeof ScoringSignalIdRoute
  '/strategy/$botId': typeof StrategyBotIdRoute
  '/trades/$tradeId': typeof TradesTradeIdRoute
  '/backtests/': typeof BacktestsIndexRoute
  '/scoring/': typeof ScoringIndexRoute
  '/trades/': typeof TradesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/features'
    | '/settings'
    | '/backtests/$runId'
    | '/bot/$botId'
    | '/scoring/$signalId'
    | '/strategy/$botId'
    | '/trades/$tradeId'
    | '/backtests/'
    | '/scoring/'
    | '/trades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/features'
    | '/settings'
    | '/backtests/$runId'
    | '/bot/$botId'
    | '/scoring/$signalId'
    | '/strategy/$botId'
    | '/trades/$tradeId'
    | '/backtests'
    | '/scoring'
    | '/trades'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/features'
    | '/settings'
    | '/backtests/$runId'
    | '/bot/$botId'
    | '/scoring/$signalId'
    | '/strategy/$botId'
    | '/trades/$tradeId'
    | '/backtests/'
    | '/scoring/'
    | '/trades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  FeaturesRoute: typeof FeaturesRoute
  SettingsRoute: typeof SettingsRoute
  BacktestsRunIdRoute: typeof BacktestsRunIdRoute
  BotBotIdRoute: typeof BotBotIdRoute
  ScoringSignalIdRoute: typeof ScoringSignalIdRoute
  StrategyBotIdRoute: typeof StrategyBotIdRoute
  TradesTradeIdRoute: typeof TradesTradeIdRoute
  BacktestsIndexRoute: typeof BacktestsIndexRoute
  ScoringIndexRoute: typeof ScoringIndexRoute
  TradesIndexRoute: typeof TradesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/': {
      id: '/trades/'
      path: '/trades'
      fullPath: '/trades/'
      preLoaderRoute: typeof TradesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoring/': {
      id: '/scoring/'
      path: '/scoring'
      fullPath: '/scoring/'
      preLoaderRoute: typeof ScoringIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtests/': {
      id: '/backtests/'
      path: '/backtests'
      fullPath: '/backtests/'
      preLoaderRoute: typeof BacktestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/$tradeId': {
      id: '/trades/$tradeId'
      path: '/trades/$tradeId'
      fullPath: '/trades/$tradeId'
      preLoaderRoute: typeof TradesTradeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy/$botId': {
      id: '/strategy/$botId'
      path: '/strategy/$botId'
      fullPath: '/strategy/$botId'
      preLoaderRoute: typeof StrategyBotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoring/$signalId': {
      id: '/scoring/$signalId'
      path: '/scoring/$signalId'
      fullPath: '/scoring/$signalId'
      preLoaderRoute: typeof ScoringSignalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot/$botId': {
      id: '/bot/$botId'
      path: '/bot/$botId'
      fullPath: '/bot/$botId'
      preLoaderRoute: typeof BotBotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtests/$runId': {
      id: '/backtests/$runId'
      path: '/backtests/$runId'
      fullPath: '/backtests/$runId'
      preLoaderRoute: typeof BacktestsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  FeaturesRoute: FeaturesRoute,
  SettingsRoute: SettingsRoute,
  BacktestsRunIdRoute: BacktestsRunIdRoute,
  BotBotIdRoute: BotBotIdRoute,
  ScoringSignalIdRoute: ScoringSignalIdRoute,
  StrategyBotIdRoute: StrategyBotIdRoute,
  TradesTradeIdRoute: TradesTradeIdRoute,
  BacktestsIndexRoute: BacktestsIndexRoute,
  ScoringIndexRoute: ScoringIndexRoute,
  TradesIndexRoute: TradesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
